# Generated by Django 2.0.1 on 2018-04-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymps', '0004_auto_20180415_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olymp',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='olymp_participants', to='accounts.Profile'),
        ),
    ]
