# Generated by Django 2.0.1 on 2018-04-16 21:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymps', '0006_auto_20180416_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingolymp',
            name='points',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=[['Summary', '0']], size=None),
        ),
    ]
