# Generated by Django 2.0.1 on 2018-04-21 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymps', '0008_auto_20180417_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olymp',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='olymp_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
