# Generated by Django 2.0.1 on 2018-04-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olymps', '0009_auto_20180421_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingolymp',
            name='user',
        ),
    ]
