# Generated by Django 2.0.1 on 2018-04-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymps', '0011_ratingolymp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='olymp',
            name='end_time',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
