# Generated by Django 2.0.1 on 2018-04-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olymps', '0012_olymp_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olymp',
            name='end_time',
        ),
    ]
