# Generated by Django 2.0.1 on 2018-04-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymps', '0013_remove_olymp_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olymp',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
