# Generated by Django 2.0.1 on 2018-04-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymps', '0015_auto_20180422_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olymp',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
