# Generated by Django 2.0.1 on 2018-04-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymps', '0016_auto_20180422_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olymp',
            name='start_time',
            field=models.DateTimeField(default='April 16, 2018, 4:51 p.m.'),
        ),
    ]
