# Generated by Django 2.0.1 on 2018-04-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymps', '0017_auto_20180423_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olymp',
            name='start_time',
            field=models.DateField(),
        ),
    ]
