# Generated by Django 2.0.1 on 2018-04-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
