# Generated by Django 2.0.1 on 2018-04-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20180409_2228'),
        ('accounts', '0007_auto_20180411_1849'),
        ('news', '0002_auto_20180417_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('object_type', models.CharField(default='', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
