# Generated by Django 2.0.1 on 2018-04-18 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem'),
        ),
    ]
