# Generated by Django 2.0.3 on 2018-04-09 16:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20180404_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkproblem',
            name='current_string',
            field=models.TextField(default='de'),
        ),
        migrations.AlterField(
            model_name='checkproblem',
            name='actions',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=[['first', 'first_hidden', 'not_in_task']], size=None),
        ),
    ]
