# Generated by Django 2.0.3 on 2018-04-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20180409_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
