# Generated by Django 2.0.3 on 2018-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20180410_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='name',
            field=models.TextField(default='de'),
        ),
    ]
