# Generated by Django 2.0.1 on 2018-05-01 23:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('problem_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=0, size=None)),
                ('lecture_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=0, size=None)),
                ('course_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=0, size=None)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='user',
        ),
        migrations.DeleteModel(
            name='PassLecture',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
