# Generated by Django 2.0.1 on 2018-05-08 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lectures', '0001_initial'),
        ('problems', '0012_auto_20180505_2011'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('courses', models.ManyToManyField(related_name='task_courses', to='courses.Course')),
                ('lectures', models.ManyToManyField(related_name='task_lectures', to='lectures.Lecture')),
                ('problemss', models.ManyToManyField(related_name='task_problems', to='problems.Problem')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
